#!/usr/bin/env ruby
#
# h2. etc/imwrc -- default imw configuration file
#
# == About
#
# This file contains the default configuration settings for this
# installation of the Infinite Monkeywrench.  Setting here override
# those in <tt>lib/imw/utils/config.rb</tt> (see the documentation for
# that file for more detail on the varioables that can be configured
# here).
#
# At the present moment, this is a plain Ruby file (though it lacks
# the <tt>.rb</tt> extension).  As the IMW develops, this will become
# a YAML file which will be parsed by
# <tt>lib/imw/utils/config.rb</tt>.
#
# Author::    (Philip flip Kromer, Dhruv Bansal) for Infinite Monkeywrench Project (mailto:coders@infochimps.org)
# Copyright:: Copyright (c) 2008 infochimps.org
# License::   GPL 3.0
# Website::   http://infinitemonkeywrench.org/
# 

module IMW
  @@paths = {
    :home      => ENV['HOME'],
    :imw_root  => File.join(File.dirname(__FILE__), '..'),

    # Data processing scripts
    :scripts_root => [:home, 'imw', 'pool'],

    # the imw library
    :imw_bin   => [:imw_root, 'bin'],
    :imw_etc   => [:imw_root, 'etc'],
    :imw_lib   => [:imw_root, 'lib'],

    # Data
    :data_root => [:home,      'imw',  'data'],
    :ripd_root => [:data_root, 'ripd'],
    :rawd_root => [:data_root, 'rawd'],
    :temp_root => [:data_root, 'temp'],
    :fixd_root => [:data_root, 'fixd'],
    :pkgd_root => [:data_root, 'pkgd'],
    :log_root  => [:data_root, 'log'],
  }
end

# puts "#{File.basename(__FILE__)}: You spend three hours configuring the settings on your Monkeywrench only to realize that you've missed your opportunity to put it to use." # at bottom
